### ISSUE TITLE
Allow connecting to plain http instead of hard coding https

### ISSUE THREAD

**Issue by knorrie** [mendix/pmCommand.py#4]
The software on the Avocent stuff is so old, that you cannot open a https connection any more from a recent OS (like, Debian Buster).

These products are discontinued, there will be no newer software updates. So, instead, we should just enable the http web server, and disable https, and then connect over plain http, while not using unsecured transport in the middle.

However, the program cannot do that currently, since it's hardcoding https.

```
~/s/pmCommand.py/src m (develop) 6-$ ./pmCommand.py admin@10.140.160.14
Enter password for admin@10.140.160.14: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 357, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.140.160.14', port=443): Max retries exceeded with url: /appliance/avtrans (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./pmCommand.py", line 201, in <module>
    cli.onecmd("login")
  File "./pmCommand.py", line 25, in onecmd
    return super(CLI, self).onecmd(line)
  File "/usr/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "./pmCommand.py", line 36, in do_login
    password)
  File "/home/knorrie/s/pmCommand.py/src/pmCommand/core.py", line 18, in login
    return self.client.login(host, username, password)
  File "/home/knorrie/s/pmCommand.py/src/pmCommand/client.py", line 88, in login
    response = self._request('login', payload=et_section)
  File "/home/knorrie/s/pmCommand.py/src/pmCommand/client.py", line 53, in _request
    response = requests.post(self._url, data=xml, headers=self._headers, verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.140.160.14', port=443): Max retries exceeded with url: /appliance/avtrans (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)')))
```

**Comment by knorrie** [comment]
Actually, since it's not useful at all any more to try https... maybe it should just hardcoded be http...

**Comment by knorrie** [comment]
@ixs you ok with this? Or do you want to be able to choose between http or https?

**Comment by ixs** [comment]
@knorrie mhm. I dunno. I think there's still value in using https because even if the encryption is not up to the latest anymore, it is still better than plaintext...

**Comment by knorrie** [comment]
That means you're also using old client side software. There is no overlap any more with recent web browsers and openssl versions. The newest supported in the avocent is older than the oldest already removed supported stuff in the libs.

Alternatively, instead of specifying a hostname or ip address, the cli tool could take a url as argument.

**Comment by knorrie** [comment]
No, since currently it takes user@host, and the user is not a basic auth user that goes into the url. Or, maybe a --ssl option to flip is to https?

I also want to change this so that it can take multiple individual pdus and combine the ports (it will obviously require unique pdu names / outlet names).

**Comment by knorrie** [comment]
So, for now, I changed it with a -u option for the user name (defaults to 'admin') and the base url as argument, which then contains either http or https.
